### ISSUE TITLE
Terraform panic using this plugin

### ISSUE THREAD

**Issue by alkalinecoffee** [juliosueiras/terraform-provider-packer#3]
We are seeing the following panic when applying a terraform config on `Terraform v0.11.8` on OSX.  Please let me know if you need the full crash log:

```
~$ tf init && tf apply
Initializing modules...
- module.ami

Initializing provider plugins...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
data.packer_json.config: Refreshing state...

Error: Error refreshing state: 1 error(s) occurred:

* module.ami.data.packer_json.config: 1 error(s) occurred:

* module.ami.data.packer_json.config: data.packer_json.config: unexpected EOF


panic: runtime error: index out of range
2018-09-10T13:37:42.197-0400 [DEBUG] plugin.terraform-provider-packer:
2018-09-10T13:37:42.197-0400 [DEBUG] plugin.terraform-provider-packer: goroutine 11 [running]:
2018-09-10T13:37:42.197-0400 [DEBUG] plugin.terraform-provider-packer: github.com/juliosueiras/terraform-provider-packer/packer.dataSourceJSONRead(0xc42029c1c0, 0x0, 0x0, 0xc4204821d0, 0xb)
2018-09-10T13:37:42.197-0400 [DEBUG] plugin.terraform-provider-packer: 	/Users/fastsupport/.go/src/github.com/juliosueiras/terraform-provider-packer/packer/data_source_json.go:432 +0x53f3
2018-09-10T13:37:42.197-0400 [DEBUG] plugin.terraform-provider-packer: github.com/hashicorp/terraform/helper/schema.(*Resource).ReadDataApply(0xc420616ea0, 0xc42014cd20, 0x0, 0x0, 0xc42048f748, 0xc42047c501, 0x80000000018)
2018-09-10T13:37:42.198-0400 [DEBUG] plugin.terraform-provider-packer: 	/Users/fastsupport/.go/src/github.com/hashicorp/terraform/helper/schema/resource.go:259 +0xb0
2018-09-10T13:37:42.198-0400 [DEBUG] plugin.terraform-provider-packer: github.com/hashicorp/terraform/helper/schema.(*Provider).ReadDataApply(0xc4202cc9a0, 0xc4201800a0, 0xc42014cd20, 0x21a3000, 0x0, 0x18)
2018-09-10T13:37:42.198-0400 [DEBUG] plugin.terraform-provider-packer: 	/Users/fastsupport/.go/src/github.com/hashicorp/terraform/helper/schema/provider.go:426 +0x9a
2018-09-10T13:37:42.198-0400 [DEBUG] plugin.terraform-provider-packer: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).ReadDataApply(0xc42048a7c0, 0xc4202c6010, 0xc4202c6180, 0x0, 0x0)
2018-09-10T13:37:42.198-0400 [DEBUG] plugin.terraform-provider-packer: 	/Users/fastsupport/.go/src/github.com/hashicorp/terraform/plugin/resource_provider.go:604 +0x4e
2018-09-10T13:37:42.198-0400 [DEBUG] plugin.terraform-provider-packer: reflect.Value.call(0xc420488360, 0xc42000e600, 0x13, 0x19fc70c, 0x4, 0xc42036bf20, 0x3, 0x3, 0xc420344ed8, 0x103bb9f, ...)
2018-09-10T13:37:42.198-0400 [DEBUG] plugin.terraform-provider-packer: 	/usr/local/Cellar/go/1.9.2/libexec/src/reflect/value.go:434 +0x905
2018-09-10T13:37:42.198-0400 [DEBUG] plugin.terraform-provider-packer: reflect.Value.Call(0xc420488360, 0xc42000e600, 0x13, 0xc420344f20, 0x3, 0x3, 0x0, 0x0, 0x0)
2018-09-10T13:37:42.198-0400 [DEBUG] plugin.terraform-provider-packer: 	/usr/local/Cellar/go/1.9.2/libexec/src/reflect/value.go:302 +0xa4
2018-09-10T13:37:42.198-0400 [DEBUG] plugin.terraform-provider-packer: net/rpc.(*service).call(0xc420485a00, 0xc42008b6d0, 0xc4201784b0, 0xc42049e380, 0xc42014d320, 0x187e660, 0xc4202c6010, 0x16, 0x187e6a0, 0xc4202c6180, ...)
2018-09-10T13:37:42.198-0400 [DEBUG] plugin.terraform-provider-packer: 	/usr/local/Cellar/go/1.9.2/libexec/src/net/rpc/server.go:381 +0x142
2018-09-10T13:37:42.198-0400 [DEBUG] plugin.terraform-provider-packer: created by net/rpc.(*Server).ServeCodec
2018-09-10T13:37:42.198-0400 [DEBUG] plugin.terraform-provider-packer: 	/usr/local/Cellar/go/1.9.2/libexec/src/net/rpc/server.go:475 +0x36b
2018/09/10 13:37:42 [ERROR] root.ami: eval: *terraform.EvalReadDataApply, err: data.packer_json.config: unexpected EOF
2018/09/10 13:37:42 [ERROR] root.ami: eval: *terraform.EvalSequence, err: data.packer_json.config: unexpected EOF
2018/09/10 13:37:42 [TRACE] [walkRefresh] Exiting eval tree: module.ami.data.packer_json.config
2018/09/10 13:37:42 [TRACE] dag/walk: upstream errored, not walking "provider.packer (close)"
2018/09/10 13:37:42 [TRACE] dag/walk: upstream errored, not walking "root"
2018-09-10T13:37:42.200-0400 [DEBUG] plugin: plugin process exited: path=/Users/joe/.terraform.d/plugins/terraform-provider-packer
2018/09/10 13:37:42 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-09-10T13:37:42.200-0400 [WARN ] plugin: error closing client during Kill: err="connection is shut down"



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

The config we're applying looks like:

```
variable app { }

data packer_json config {
  builders {
    amazon_ebs {
      source_ami = "ami-..."

      ami_name          = "something"
      instance_type     = "t2.medium"
      region            = "us-east-1"
      security_group_id = "sg-..."
      subnet_id         = "subnet-..."
      vpc_id            = "vpc-..."

      access_key    = "..."
      secret_key    = "..."
    }
  }

  provisioners {
    shell {
      execute_order = 1
      inline = ["yum update"]
    }
  }
}
```

**Comment by alkalinecoffee** [comment]
We found that if the `source_ami_filter {}` block is missing from the `amazon_ebs` block it will trigger this panic.

**Comment by juliosueiras** [comment]
can you try it again with v0.1.1?

**Comment by alkalinecoffee** [comment]
Looks good, thanks!
